title: ChanceCo Industries
author: jchance
description: Documentation for ChanceCo Industries builds on c.nerd.nu
theme: just-the-docs

url: https://chanceco.industries

aux_links:
  Nerd.nu: https:nerd.nu
